stages:
  - install
  - build
  - test

# Installiere alle Abhängigkeiten
install_dependencies:
  stage: install
  image: node:16
  script:
    - npm install  # Installiert alle Projekt-Abhängigkeiten
  only:
    - master  # Diese Pipeline wird nur für Pushes auf den Master-Branch ausgeführt

# Baue das Projekt (z.B. Transpiliere TypeScript, Bundle JS, etc.)
build_app:
  stage: build
  image: node:16
  script:
    - npm run build  # Führt den Build-Prozess aus (z.B. mit Webpack oder einem anderen Bundler)
  only:
    - master  # Wird nur auf den Master-Branch angewendet

# Teste die Anwendung
test_app:
  stage: test
  image: node:16
  script:
    - npm run test  # Führt Tests durch, die mit npm installierten Test-Frameworks konfiguriert sind
  only:
    - master  # Wird nur auf den Master-Branch angewendet

# GitLab CI/CD Tokens und API-Setup für den Test
# GitLab API Token und Projekt ID werden als Umgebungsvariablen gesetzt, wenn nötig.
variables:
  CI_PROJECT_ID: "1"  # Dies ist die Projekt-ID, die in GitLab zu deinem Projekt gehört
  CI_API_TOKEN: "${CI_JOB_TOKEN}"  # Das CI Job Token für den API-Zugang
